server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://db.qianxunclub.com:3306/permanent?characterEncoding=utf-8&useSSL=true
    username: permanent
    password: Permanent123
    driver-class-name: com.mysql.jdbc.Driver

config:
  oauth:
    qq:
      clientId: 101372806
      clientSecret: 618ebc3de5734fb7623da8037096836d
      redirectUrl: http://permanent.qianxunclub.com/api/auth/callback