server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://db.qianxunclub.com:3306/permanent?characterEncoding=utf-8&useSSL=true
    username: permanent
    password: Permanent123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379

config:
  session:
    # session 超时时间，单位：小时
    timeout: 24
  oauth:
    qq:
      clientId: 101372806
      clientSecret: 618ebc3de5734fb7623da8037096836d
      redirectUrl: http://permanent.qianxunclub.com/api/auth/callback