server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://db.qianxunclub.com:3306/permanent?characterEncoding=utf-8&useSSL=true
    username: permanent
    password: Permanent123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ecs.qianxunclub.com
    port: 6379
    password: 123456

swagger:
  enabled: true
  title: 记忆卡片
  description: 记忆卡片
  webBasePackage: com.qianxunclub.permanent.controller
  author: 千寻啊千寻
  url: permanent.qianxunclub.com
  email: qianxunclub@qq.com

config:
  session:
    # session 超时时间，单位：小时
    timeout: 24
  oauth:
    qq:
      clientId: 101372806
      clientSecret: 618ebc3de5734fb7623da8037096836d
      redirectUrl: http://permanent.qianxunclub.com/api/auth/callback
    wxss:
      appId: wx1bd815cb5a4bac51
      appSecret: b0cbcf514dba1172e6ff3856c4d5b1e4